#!/usr/bin/env python3
"""Generate the Vale STE style from the Simplified Technical English rule source.

The rule source is the deck skill's ``config/rules.json``. This repository
keeps a frozen snapshot of it under ``.vale/ste-source.json`` with the
source commit, path, and digest recorded beside it in
``.vale/ste-source.yaml``. The generator reads the snapshot, or a rule
file named with ``--rules``, and writes deterministic YAML under
``.vale/styles/STE/``. ``--check`` regenerates into memory and fails when
any generated file differs or when the snapshot digest does not match its
record, so a stale style never passes a commit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / ".vale" / "ste-source.json"
RECORD = ROOT / ".vale" / "ste-source.yaml"
STYLE = ROOT / ".vale" / "styles" / "STE"
# Core is hand-written except for the one rule that shares the OVERUSE
# list, so the term list has one source. Only that file is generated.
CORE = ROOT / ".vale" / "styles" / "Core"

# One-word replacements the rule source bans without naming a swap. Vale's
# substitution rule needs a target, so the pairs live here. A banned word
# with no entry falls into the plain existence rule below.
SWAPS = {
    "utilize": "use",
    "utilizes": "uses",
    "utilizing": "using",
    "leverage": "use",
    "leverages": "uses",
    "leveraging": "using",
    "commence": "start",
    "commences": "starts",
    "initiate": "start",
    "initiates": "starts",
    "obtain": "get",
    "obtains": "gets",
    "acquire": "get",
    "acquires": "gets",
    "demonstrate": "show",
    "demonstrates": "shows",
    "additionally": "also",
    "furthermore": "also",
    "moreover": "also",
    "whilst": "while",
    "amongst": "among",
    "numerous": "many",
    "prior to": "before",
    "subsequent to": "after",
    "in order to": "to",
    "a variety of": "several",
    "in the event that": "if",
    "due to the fact that": "because",
    "spin up": "start",
    "spin down": "stop",
    "reach out": "contact",
    "kick off": "start",
    "kicks off": "starts",
    "roll out": "release",
    "rolls out": "releases",
    "tear down": "remove",
    "ramp up": "increase",
    "wire up": "connect",
    "wires up": "connects",
    "wired up": "connected",
    "wiring up": "connecting",
}

# Words that are fine once and a tell when they recur. One occurrence rule
# per lemma counts its forms in one paragraph, so a second use warns and a
# single use passes. The rule source cannot hold this list: its linter
# rejects unknown keys, and a blanket ban is what these words must avoid.
OVERUSE = {
    "Arm": ["arm", "arms", "armed", "arming"],
    "Gate": ["gate", "gates", "gated", "gating"],
    "Knob": ["knob", "knobs"],
    "Landscape": ["landscape", "landscapes"],
    "Lane": ["lane", "lanes"],
    "Significant": ["significant", "significantly"],
    "Surface": ["surface", "surfaces", "surfaced", "surfacing"],
    "Various": ["various"],
}
# The OVERUSE lemmas that are metaphor nouns. Each needs a definition at
# first use (Core.UndefinedTerm). An adjective is counted, never defined.
TERMS = {"Arm", "Gate", "Knob", "Landscape", "Lane", "Surface"}
assert TERMS <= set(OVERUSE), "every term must also be an OVERUSE lemma"

HEADER = "# Generated by scripts/generate-vale-style.py from the STE rule source. Do not edit.\n"


def load_rules(path: Path) -> dict:
    """Load the rule source JSON or exit with a readable error."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise SystemExit(f"generate-vale-style: cannot read {path}: {error}") from error


def yaml_list(items: list[str]) -> str:
    """Render a YAML block sequence of quoted strings."""
    return "".join(f"  - {json.dumps(item)}\n" for item in items)


def yaml_swap(pairs: dict[str, str]) -> str:
    """Render a YAML mapping of quoted keys to quoted values."""
    return "".join(f"  {json.dumps(key)}: {json.dumps(value)}\n" for key, value in pairs.items())


def render(rules: dict) -> dict[str, str]:
    """Return the generated files keyed by name under the style directory."""
    banned = list(rules.get("bannedWords", [])) + list(rules.get("bannedPhrases", []))
    phrasal = list(rules.get("phrasalVerbs", []))
    substitutions = {word: SWAPS[word] for word in banned if word in SWAPS}
    phrasal_swaps = {verb: SWAPS[verb] for verb in phrasal if verb in SWAPS}
    existence = sorted({word for word in banned if word not in SWAPS})
    phrasal_only = sorted({verb for verb in phrasal if verb not in SWAPS})
    fillers = sorted(set(rules.get("fillerPhrases", [])))
    marketing = sorted(set(rules.get("marketing", [])))
    verb_only = sorted(set(rules.get("verbOnlyWords", [])))
    strict = sorted(set(rules.get("strictBannedWords", [])))

    # Levels: STE advises, it does not fail a run. The structural rules
    # (semicolon, contraction) warn. Vocabulary rules suggest, since one
    # plain-word swap is taste and the owner's own rules carry the hard
    # bans. Only an overuse rule warns, because recurrence is the tell.
    files = {
        "Semicolons.yml": HEADER
        + "extends: existence\n"
        + 'message: "Do not use semicolons in prose. Split the sentence."\n'
        + "level: warning\nscope: sentence\nnonword: true\ntokens:\n  - ';'\n",
        "Contractions.yml": HEADER
        + "extends: existence\n"
        + "message: \"Do not use the contraction '%s'. Write the full form.\"\n"
        + "level: warning\nscope: sentence\nignorecase: true\ntokens:\n"
        + "  - \\b(?:don't|doesn't|didn't|can't|won't|isn't|aren't|wasn't|weren't|couldn't|shouldn't|wouldn't|it's|that's|there's|let's|we're|you're|they're|I'm|we've|you've|they've|hasn't|haven't)\\b\n",
        "Substitutions.yml": HEADER
        + "extends: substitution\n"
        + "message: \"Use '%s' instead of '%s'.\"\n"
        + "level: suggestion\nscope: sentence\nignorecase: true\naction:\n  name: replace\nswap:\n"
        + yaml_swap(dict(sorted(substitutions.items()))),
        "PhrasalVerbs.yml": HEADER
        + "extends: substitution\n"
        + "message: \"Do not use the phrasal verb '%s'. Use '%s'.\"\n"
        + "level: suggestion\nscope: sentence\nignorecase: true\naction:\n  name: replace\nswap:\n"
        + yaml_swap(dict(sorted(phrasal_swaps.items()))),
        "BannedWords.yml": HEADER
        + "extends: existence\n"
        + "message: \"Do not use '%s'. Choose a plain word.\"\n"
        + "level: suggestion\nscope: sentence\nignorecase: true\ntokens:\n"
        + yaml_list(existence + phrasal_only),
        "FillerPhrases.yml": HEADER
        + "extends: existence\n"
        + "message: \"Delete the filler '%s'.\"\n"
        + "level: suggestion\nscope: sentence\nignorecase: true\ntokens:\n"
        + yaml_list(fillers),
        "Marketing.yml": HEADER
        + "extends: existence\n"
        + "message: \"'%s' is marketing language. State the fact.\"\n"
        + "level: suggestion\nscope: sentence\nignorecase: true\ntokens:\n"
        + yaml_list(marketing),
        "VerbOnlyWords.yml": HEADER
        + "extends: existence\n"
        + "message: \"'%s' is a jargon verb here. Use a literal verb.\"\n"
        + "level: suggestion\nscope: sentence\nignorecase: true\ntokens:\n"
        + yaml_list(verb_only),
        # The deck applies these only under lint.py --strict (procedures and
        # runbooks), and "shall" is the requirement keyword in every spec.
        # A suggestion never fails a run; MinAlertLevel = suggestion shows it.
        "StrictWords.yml": HEADER
        + "extends: existence\n"
        + "message: \"Strict mode: avoid '%s' in procedures and runbooks.\"\n"
        + "level: suggestion\nscope: sentence\nignorecase: true\ntokens:\n"
        + yaml_list(strict),
    }
    # A term may appear twice in a paragraph: once defined in italics, once
    # used. Paragraph scope strips the markers, so the count cannot tell
    # the two apart. An adjective has no definition and gets one use.
    for lemma, forms in sorted(OVERUSE.items()):
        limit = 2 if lemma in TERMS else 1
        files[f"Overused{lemma}.yml"] = (
            HEADER
            + "extends: occurrence\n"
            + f"message: \"'{forms[0]}' appears more than {'twice' if limit == 2 else 'once'} in this paragraph. Name the thing it stands for.\"\n"
            + f"level: warning\nscope: paragraph\nignorecase: true\nmax: {limit}\n"
            + f"token: '\\b(?:{'|'.join(forms)})\\b'\n"
        )
    return files


def render_core() -> dict[str, str]:
    """Return the generated Core files: the term rule that shares OVERUSE."""
    nouns = "|".join(sorted(lemma.lower() for lemma in TERMS))
    return {
        "UndefinedTerm.yml": HEADER
        + "# Deslop (rule): a metaphor noun such as \"gate\" means nothing until the\n"
        + "# text says which check, file, or flag it stands for. A defined term is\n"
        + "# set in italics at first use, so an italic, bold, or backticked form\n"
        + "# anywhere in the text counts as the definition. The nouns are the\n"
        + "# TERMS subset of OVERUSE, so one list serves this rule and STE.Overused*.\n"
        + "# Raw scope, because Vale strips the markers before any other scope.\n"
        + "extends: conditional\n"
        + "message: \"'%s' is never defined here. Set it in italics at first use and say what it is (rule Deslop).\"\n"
        + "level: warning\nignorecase: true\nscope: raw\n"
        + f"first: '\\b({nouns})s?\\b'\n"
        + f"second: '[*_`]({nouns})s?[*_`]'\n",
    }


def digest(path: Path) -> str:
    """Return the hex SHA-256 of a file."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_record() -> dict[str, str]:
    """Read the flat key: value snapshot record without a YAML dependency."""
    record: dict[str, str] = {}
    if not RECORD.is_file():
        return record
    for line in RECORD.read_text(encoding="utf-8").splitlines():
        if ":" in line and not line.startswith("#"):
            key, _, value = line.partition(":")
            record[key.strip()] = value.strip()
    return record


def check(rules_path: Path) -> int:
    """Report stale, missing, or foreign style files. Return 1 when any exist."""
    problems: list[str] = []
    if rules_path == SNAPSHOT:
        record = read_record()
        recorded = record.get("sha256", "")
        actual = digest(SNAPSHOT) if SNAPSHOT.is_file() else ""
        if not actual:
            problems.append(f"{SNAPSHOT} is missing")
        elif recorded != actual:
            problems.append(f"{SNAPSHOT} digest {actual[:12]} does not match the recorded {recorded[:12]}")
    expected = render(load_rules(rules_path))
    present = {path.name for path in STYLE.glob("*.yml")} if STYLE.is_dir() else set()
    for name, content in expected.items():
        target = STYLE / name
        if not target.is_file():
            problems.append(f"{target} is missing")
        elif target.read_text(encoding="utf-8") != content:
            problems.append(f"{target} is stale")
    for extra in sorted(present - set(expected)):
        problems.append(f"{STYLE / extra} is not generated by this script")
    # Core keeps hand-written rules beside the generated one, so only the
    # generated file is compared and nothing there is foreign.
    for name, content in render_core().items():
        target = CORE / name
        if not target.is_file():
            problems.append(f"{target} is missing")
        elif target.read_text(encoding="utf-8") != content:
            problems.append(f"{target} is stale")
    for problem in problems:
        print(f"generate-vale-style: {problem}", file=sys.stderr)
    if problems:
        print("generate-vale-style: run scripts/generate-vale-style.py", file=sys.stderr)
    return 1 if problems else 0


def write(rules_path: Path) -> int:
    """Write every generated style file and remove foreign ones."""
    STYLE.mkdir(parents=True, exist_ok=True)
    expected = render(load_rules(rules_path))
    for name, content in expected.items():
        (STYLE / name).write_text(content, encoding="utf-8")
    for extra in STYLE.glob("*.yml"):
        if extra.name not in expected:
            extra.unlink()
    CORE.mkdir(parents=True, exist_ok=True)
    core = render_core()
    for name, content in core.items():
        (CORE / name).write_text(content, encoding="utf-8")
    print(f"generate-vale-style: wrote {len(expected)} files under {STYLE} and {len(core)} under {CORE}")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Parse arguments and dispatch to check or write."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0], allow_abbrev=False)
    parser.add_argument("--rules", type=Path, default=SNAPSHOT, help="rule source JSON (default: the frozen snapshot)")
    parser.add_argument("--check", action="store_true", help="verify the generated style instead of writing it")
    args = parser.parse_args(argv)
    return check(args.rules) if args.check else write(args.rules)


if __name__ == "__main__":
    sys.exit(main())
